<template>
    <el-table
        :data="data"
        stripe
        border
        fit
        highlight-current-row
        >
        <el-table-column
            prop="dec"
            label="十进制"
            >
        </el-table-column>
        <!--<el-table-column
            prop="oct"
            label="八进制"
            width="180">
        </el-table-column>-->
        <el-table-column
            prop="hex"
            label="十六进制">
        </el-table-column>
        <el-table-column
            prop="bin"
            label="二进制">
        </el-table-column>
        <el-table-column
            prop="symbol"
            label="符号">
        </el-table-column>
        <el-table-column
            prop="htmlCode"
            label="html代码">
        </el-table-column>
        <el-table-column
            prop="name"
            label="名称"
            width="300">
        </el-table-column>
    </el-table>
</template>

<script>
    export default {
        name: 'ascii',
        data() {
            return {
                data: [{
                    'oct': '000',
                    'symbol': 'NUL',
                    'dec': '0',
                    'bin': '00000000',
                    'htmlCode': '&#000;',
                    'name': '空字符（Null）',
                    'hex': '00'
                }, {
                    'oct': '001',
                    'symbol': 'SOH',
                    'dec': '1',
                    'bin': '00000001',
                    'htmlCode': '&#001;',
                    'name': '标题开始',
                    'hex': '01'
                }, {
                    'oct': '002',
                    'symbol': 'STX',
                    'dec': '2',
                    'bin': '00000010',
                    'htmlCode': '&#002;',
                    'name': '本文开始',
                    'hex': '02'
                }, {
                    'oct': '003',
                    'symbol': 'ETX',
                    'dec': '3',
                    'bin': '00000011',
                    'htmlCode': '&#003;',
                    'name': '本文结束',
                    'hex': '03'
                }, {
                    'oct': '004',
                    'symbol': 'EOT',
                    'dec': '4',
                    'bin': '00000100',
                    'htmlCode': '&#004;',
                    'name': '传输结束',
                    'hex': '04'
                }, {
                    'oct': '005',
                    'symbol': 'ENQ',
                    'dec': '5',
                    'bin': '00000101',
                    'htmlCode': '&#005;',
                    'name': '请求',
                    'hex': '05'
                }, {
                    'oct': '006',
                    'symbol': 'ACK',
                    'dec': '6',
                    'bin': '00000110',
                    'htmlCode': '&#006;',
                    'name': '确认回应',
                    'hex': '06'
                }, {
                    'oct': '007',
                    'symbol': 'BEL',
                    'dec': '7',
                    'bin': '00000111',
                    'htmlCode': '&#007;',
                    'name': '响铃',
                    'hex': '07'
                }, {
                    'oct': '010',
                    'symbol': 'BS',
                    'dec': '8',
                    'bin': '00001000',
                    'htmlCode': '&#008;',
                    'name': '退格',
                    'hex': '08'
                }, {
                    'oct': '011',
                    'symbol': 'HT',
                    'dec': '9',
                    'bin': '00001001',
                    'htmlCode': '&#009;',
                    'name': '水平定位符号',
                    'hex': '09'
                }, {
                    'oct': '012',
                    'symbol': 'LF',
                    'dec': '10',
                    'bin': '00001010',
                    'htmlCode': '&#010;',
                    'name': '换行键',
                    'hex': '0A'
                }, {
                    'oct': '013',
                    'symbol': 'VT',
                    'dec': '11',
                    'bin': '00001011',
                    'htmlCode': '&#011;',
                    'name': '垂直定位符号',
                    'hex': '0B'
                }, {
                    'oct': '014',
                    'symbol': 'FF',
                    'dec': '12',
                    'bin': '00001100',
                    'htmlCode': '&#012;',
                    'name': '换页键',
                    'hex': '0C'
                }, {
                    'oct': '015',
                    'symbol': 'CR',
                    'dec': '13',
                    'bin': '00001101',
                    'htmlCode': '&#013;',
                    'name': '归位键',
                    'hex': '0D'
                }, {
                    'oct': '016',
                    'symbol': 'SO',
                    'dec': '14',
                    'bin': '00001110',
                    'htmlCode': '&#014;',
                    'name': '取消变换（Shift out）',
                    'hex': '0E'
                }, {
                    'oct': '017',
                    'symbol': 'SI',
                    'dec': '15',
                    'bin': '00001111',
                    'htmlCode': '&#015;',
                    'name': '启用变换（Shift in）',
                    'hex': '0F'
                }, {
                    'oct': '020',
                    'symbol': 'DLE',
                    'dec': '16',
                    'bin': '00010000',
                    'htmlCode': '&#016;',
                    'name': '跳出数据通讯',
                    'hex': '10'
                }, {
                    'oct': '021',
                    'symbol': 'DC1',
                    'dec': '17',
                    'bin': '00010001',
                    'htmlCode': '&#017;',
                    'name': '设备控制一（XON 启用软件速度控制）',
                    'hex': '11'
                }, {
                    'oct': '022',
                    'symbol': 'DC2',
                    'dec': '18',
                    'bin': '00010010',
                    'htmlCode': '&#018;',
                    'name': '设备控制二',
                    'hex': '12'
                }, {
                    'oct': '023',
                    'symbol': 'DC3',
                    'dec': '19',
                    'bin': '00010011',
                    'htmlCode': '&#019;',
                    'name': '设备控制三（XOFF 停用软件速度控制）',
                    'hex': '13'
                }, {
                    'oct': '024',
                    'symbol': 'DC4',
                    'dec': '20',
                    'bin': '00010100',
                    'htmlCode': '&#020;',
                    'name': '设备控制四',
                    'hex': '14'
                }, {
                    'oct': '025',
                    'symbol': 'NAK',
                    'dec': '21',
                    'bin': '00010101',
                    'htmlCode': '&#021;',
                    'name': '确认失败回应',
                    'hex': '15'
                }, {
                    'oct': '026',
                    'symbol': 'SYN',
                    'dec': '22',
                    'bin': '00010110',
                    'htmlCode': '&#022;',
                    'name': '同步用暂停',
                    'hex': '16'
                }, {
                    'oct': '027',
                    'symbol': 'ETB',
                    'dec': '23',
                    'bin': '00010111',
                    'htmlCode': '&#023;',
                    'name': '区块传输结束',
                    'hex': '17'
                }, {
                    'oct': '030',
                    'symbol': 'CAN',
                    'dec': '24',
                    'bin': '00011000',
                    'htmlCode': '&#024;',
                    'name': '取消',
                    'hex': '18'
                }, {
                    'oct': '031',
                    'symbol': 'EM',
                    'dec': '25',
                    'bin': '00011001',
                    'htmlCode': '&#025;',
                    'name': '连接介质中断',
                    'hex': '19'
                }, {
                    'oct': '032',
                    'symbol': 'SUB',
                    'dec': '26',
                    'bin': '00011010',
                    'htmlCode': '&#026;',
                    'name': '替换',
                    'hex': '1A'
                }, {
                    'oct': '033',
                    'symbol': 'ESC',
                    'dec': '27',
                    'bin': '00011011',
                    'htmlCode': '&#027;',
                    'name': '跳出',
                    'hex': '1B'
                }, {
                    'oct': '034',
                    'symbol': 'FS',
                    'dec': '28',
                    'bin': '00011100',
                    'htmlCode': '&#028;',
                    'name': '文件分割符',
                    'hex': '1C'
                }, {
                    'oct': '035',
                    'symbol': 'GS',
                    'dec': '29',
                    'bin': '00011101',
                    'htmlCode': '&#029;',
                    'name': '组群分隔符',
                    'hex': '1D'
                }, {
                    'oct': '036',
                    'symbol': 'RS',
                    'dec': '30',
                    'bin': '00011110',
                    'htmlCode': '&#030;',
                    'name': '记录分隔符',
                    'hex': '1E'
                }, {
                    'oct': '037',
                    'symbol': 'US',
                    'dec': '31',
                    'bin': '00011111',
                    'htmlCode': '&#031;',
                    'name': '单元分隔符',
                    'hex': '1F'
                }, {
                    'oct': '040',
                    'symbol': ' ',
                    'dec': '32',
                    'bin': '00100000',
                    'htmlCode': '&#32;',
                    'name': '（空格）(␠)',
                    'hex': '20'
                }, {
                    'oct': '041',
                    'symbol': '!',
                    'dec': '33',
                    'bin': '00100001',
                    'htmlCode': '&#33;',
                    'name': '!',
                    'hex': '21'
                }, {
                    'oct': '042',
                    'symbol': '"',
                    'dec': '34',
                    'bin': '00100010',
                    'htmlCode': '&#34;',
                    'name': '"',
                    'hex': '22'
                }, {
                    'oct': '043',
                    'symbol': '#',
                    'dec': '35',
                    'bin': '00100011',
                    'htmlCode': '&#35;',
                    'name': '#',
                    'hex': '23'
                }, {
                    'oct': '044',
                    'symbol': '$',
                    'dec': '36',
                    'bin': '00100100',
                    'htmlCode': '&#36;',
                    'name': '$',
                    'hex': '24'
                }, {
                    'oct': '045',
                    'symbol': '%',
                    'dec': '37',
                    'bin': '00100101',
                    'htmlCode': '&#37;',
                    'name': ' %',
                    'hex': '25'
                }, {
                    'oct': '046',
                    'symbol': '&',
                    'dec': '38',
                    'bin': '00100110',
                    'htmlCode': '&#38;',
                    'name': '&',
                    'hex': '26'
                }, {
                    'oct': '047',
                    'symbol': '\'',
                    'dec': '39',
                    'bin': '00100111',
                    'htmlCode': '&#39;',
                    'name': '\'',
                    'hex': '27'
                }, {
                    'oct': '050',
                    'symbol': '(',
                    'dec': '40',
                    'bin': '00101000',
                    'htmlCode': '&#40;',
                    'name': '(',
                    'hex': '28'
                }, {
                    'oct': '051',
                    'symbol': ')',
                    'dec': '41',
                    'bin': '00101001',
                    'htmlCode': '&#41;',
                    'name': ')',
                    'hex': '29'
                }, {
                    'oct': '052',
                    'symbol': '*',
                    'dec': '42',
                    'bin': '00101010',
                    'htmlCode': '&#42;',
                    'name': '*',
                    'hex': '2A'
                }, {
                    'oct': '053',
                    'symbol': '+',
                    'dec': '43',
                    'bin': '00101011',
                    'htmlCode': '&#43;',
                    'name': '+',
                    'hex': '2B'
                }, {
                    'oct': '054',
                    'symbol': ',',
                    'dec': '44',
                    'bin': '00101100',
                    'htmlCode': '&#44;',
                    'name': ',',
                    'hex': '2C'
                }, {
                    'oct': '055',
                    'symbol': '-',
                    'dec': '45',
                    'bin': '00101101',
                    'htmlCode': '&#45;',
                    'name': '-',
                    'hex': '2D'
                }, {
                    'oct': '056',
                    'symbol': '.',
                    'dec': '46',
                    'bin': '00101110',
                    'htmlCode': '&#46;',
                    'name': '.',
                    'hex': '2E'
                }, {
                    'oct': '057',
                    'symbol': '/',
                    'dec': '47',
                    'bin': '00101111',
                    'htmlCode': '&#47;',
                    'name': '/',
                    'hex': '2F'
                }, {
                    'oct': '060',
                    'symbol': '0',
                    'dec': '48',
                    'bin': '00110000',
                    'htmlCode': '&#48;',
                    'name': '0',
                    'hex': '30'
                }, {
                    'oct': '061',
                    'symbol': '1',
                    'dec': '49',
                    'bin': '00110001',
                    'htmlCode': '&#49;',
                    'name': '1',
                    'hex': '31'
                }, {
                    'oct': '062',
                    'symbol': '2',
                    'dec': '50',
                    'bin': '00110010',
                    'htmlCode': '&#50;',
                    'name': '2',
                    'hex': '32'
                }, {
                    'oct': '063',
                    'symbol': '3',
                    'dec': '51',
                    'bin': '00110011',
                    'htmlCode': '&#51;',
                    'name': '3',
                    'hex': '33'
                }, {
                    'oct': '064',
                    'symbol': '4',
                    'dec': '52',
                    'bin': '00110100',
                    'htmlCode': '&#52;',
                    'name': '4',
                    'hex': '34'
                }, {
                    'oct': '065',
                    'symbol': '5',
                    'dec': '53',
                    'bin': '00110101',
                    'htmlCode': '&#53;',
                    'name': '5',
                    'hex': '35'
                }, {
                    'oct': '066',
                    'symbol': '6',
                    'dec': '54',
                    'bin': '00110110',
                    'htmlCode': '&#54;',
                    'name': '6',
                    'hex': '36'
                }, {
                    'oct': '067',
                    'symbol': '7',
                    'dec': '55',
                    'bin': '00110111',
                    'htmlCode': '&#55;',
                    'name': '7',
                    'hex': '37'
                }, {
                    'oct': '070',
                    'symbol': '8',
                    'dec': '56',
                    'bin': '00111000',
                    'htmlCode': '&#56;',
                    'name': '8',
                    'hex': '38'
                }, {
                    'oct': '071',
                    'symbol': '9',
                    'dec': '57',
                    'bin': '00111001',
                    'htmlCode': '&#57;',
                    'name': '9',
                    'hex': '39'
                }, {
                    'oct': '072',
                    'symbol': ':',
                    'dec': '58',
                    'bin': '00111010',
                    'htmlCode': '&#58;',
                    'name': ':',
                    'hex': '3A'
                }, {
                    'oct': '073',
                    'symbol': ';',
                    'dec': '59',
                    'bin': '00111011',
                    'htmlCode': '&#59;',
                    'name': ';',
                    'hex': '3B'
                }, {
                    'oct': '074',
                    'symbol': '<',
                    'dec': '60',
                    'bin': '00111100',
                    'htmlCode': '&#60;',
                    'name': '<',
                    'hex': '3C'
                }, {
                    'oct': '075',
                    'symbol': '=',
                    'dec': '61',
                    'bin': '00111101',
                    'htmlCode': '&#61;',
                    'name': '=',
                    'hex': '3D'
                }, {
                    'oct': '076',
                    'symbol': '>',
                    'dec': '62',
                    'bin': '00111110',
                    'htmlCode': '&#62;',
                    'name': '>',
                    'hex': '3E'
                }, {
                    'oct': '077',
                    'symbol': '?',
                    'dec': '63',
                    'bin': '00111111',
                    'htmlCode': '&#63;',
                    'name': '?',
                    'hex': '3F'
                }, {
                    'oct': '100',
                    'symbol': '@',
                    'dec': '64',
                    'bin': '01000000',
                    'htmlCode': '&#64;',
                    'name': '@',
                    'hex': '40'
                }, {
                    'oct': '101',
                    'symbol': 'A',
                    'dec': '65',
                    'bin': '01000001',
                    'htmlCode': '&#65;',
                    'name': 'A',
                    'hex': '41'
                }, {
                    'oct': '102',
                    'symbol': 'B',
                    'dec': '66',
                    'bin': '01000010',
                    'htmlCode': '&#66;',
                    'name': 'B',
                    'hex': '42'
                }, {
                    'oct': '103',
                    'symbol': 'C',
                    'dec': '67',
                    'bin': '01000011',
                    'htmlCode': '&#67;',
                    'name': 'C',
                    'hex': '43'
                }, {
                    'oct': '104',
                    'symbol': 'D',
                    'dec': '68',
                    'bin': '01000100',
                    'htmlCode': '&#68;',
                    'name': 'D',
                    'hex': '44'
                }, {
                    'oct': '105',
                    'symbol': 'E',
                    'dec': '69',
                    'bin': '01000101',
                    'htmlCode': '&#69;',
                    'name': 'E',
                    'hex': '45'
                }, {
                    'oct': '106',
                    'symbol': 'F',
                    'dec': '70',
                    'bin': '01000110',
                    'htmlCode': '&#70;',
                    'name': 'F',
                    'hex': '46'
                }, {
                    'oct': '107',
                    'symbol': 'G',
                    'dec': '71',
                    'bin': '01000111',
                    'htmlCode': '&#71;',
                    'name': 'G',
                    'hex': '47'
                }, {
                    'oct': '110',
                    'symbol': 'H',
                    'dec': '72',
                    'bin': '01001000',
                    'htmlCode': '&#72;',
                    'name': 'H',
                    'hex': '48'
                }, {
                    'oct': '111',
                    'symbol': 'I',
                    'dec': '73',
                    'bin': '01001001',
                    'htmlCode': '&#73;',
                    'name': 'I',
                    'hex': '49'
                }, {
                    'oct': '112',
                    'symbol': 'J',
                    'dec': '74',
                    'bin': '01001010',
                    'htmlCode': '&#74;',
                    'name': 'J',
                    'hex': '4A'
                }, {
                    'oct': '113',
                    'symbol': 'K',
                    'dec': '75',
                    'bin': '01001011',
                    'htmlCode': '&#75;',
                    'name': 'K',
                    'hex': '4B'
                }, {
                    'oct': '114',
                    'symbol': 'L',
                    'dec': '76',
                    'bin': '01001100',
                    'htmlCode': '&#76;',
                    'name': 'L',
                    'hex': '4C'
                }, {
                    'oct': '115',
                    'symbol': 'M',
                    'dec': '77',
                    'bin': '01001101',
                    'htmlCode': '&#77;',
                    'name': 'M',
                    'hex': '4D'
                }, {
                    'oct': '116',
                    'symbol': 'N',
                    'dec': '78',
                    'bin': '01001110',
                    'htmlCode': '&#78;',
                    'name': 'N',
                    'hex': '4E'
                }, {
                    'oct': '117',
                    'symbol': 'O',
                    'dec': '79',
                    'bin': '01001111',
                    'htmlCode': '&#79;',
                    'name': 'O',
                    'hex': '4F'
                }, {
                    'oct': '120',
                    'symbol': 'P',
                    'dec': '80',
                    'bin': '01010000',
                    'htmlCode': '&#80;',
                    'name': 'P',
                    'hex': '50'
                }, {
                    'oct': '121',
                    'symbol': 'Q',
                    'dec': '81',
                    'bin': '01010001',
                    'htmlCode': '&#81;',
                    'name': 'Q',
                    'hex': '51'
                }, {
                    'oct': '122',
                    'symbol': 'R',
                    'dec': '82',
                    'bin': '01010010',
                    'htmlCode': '&#82;',
                    'name': 'R',
                    'hex': '52'
                }, {
                    'oct': '123',
                    'symbol': 'S',
                    'dec': '83',
                    'bin': '01010011',
                    'htmlCode': '&#83;',
                    'name': 'S',
                    'hex': '53'
                }, {
                    'oct': '124',
                    'symbol': 'T',
                    'dec': '84',
                    'bin': '01010100',
                    'htmlCode': '&#84;',
                    'name': 'T',
                    'hex': '54'
                }, {
                    'oct': '125',
                    'symbol': 'U',
                    'dec': '85',
                    'bin': '01010101',
                    'htmlCode': '&#85;',
                    'name': 'U',
                    'hex': '55'
                }, {
                    'oct': '126',
                    'symbol': 'V',
                    'dec': '86',
                    'bin': '01010110',
                    'htmlCode': '&#86;',
                    'name': 'V',
                    'hex': '56'
                }, {
                    'oct': '127',
                    'symbol': 'W',
                    'dec': '87',
                    'bin': '01010111',
                    'htmlCode': '&#87;',
                    'name': 'W',
                    'hex': '57'
                }, {
                    'oct': '130',
                    'symbol': 'X',
                    'dec': '88',
                    'bin': '01011000',
                    'htmlCode': '&#88;',
                    'name': 'X',
                    'hex': '58'
                }, {
                    'oct': '131',
                    'symbol': 'Y',
                    'dec': '89',
                    'bin': '01011001',
                    'htmlCode': '&#89;',
                    'name': 'Y',
                    'hex': '59'
                }, {
                    'oct': '132',
                    'symbol': 'Z',
                    'dec': '90',
                    'bin': '01011010',
                    'htmlCode': '&#90;',
                    'name': 'Z',
                    'hex': '5A'
                }, {
                    'oct': '133',
                    'symbol': '[',
                    'dec': '91',
                    'bin': '01011011',
                    'htmlCode': '&#91;',
                    'name': '[',
                    'hex': '5B'
                }, {
                    'oct': '134',
                    'symbol': '\\',
                    'dec': '92',
                    'bin': '01011100',
                    'htmlCode': '&#92;',
                    'name': '\\',
                    'hex': '5C'
                }, {
                    'oct': '135',
                    'symbol': ']',
                    'dec': '93',
                    'bin': '01011101',
                    'htmlCode': '&#93;',
                    'name': ']',
                    'hex': '5D'
                }, {
                    'oct': '136',
                    'symbol': '^',
                    'dec': '94',
                    'bin': '01011110',
                    'htmlCode': '&#94;',
                    'name': '^',
                    'hex': '5E'
                }, {
                    'oct': '137',
                    'symbol': '_',
                    'dec': '95',
                    'bin': '01011111',
                    'htmlCode': '&#95;',
                    'name': '_',
                    'hex': '5F'
                }, {
                    'oct': '140',
                    'symbol': '`',
                    'dec': '96',
                    'bin': '01100000',
                    'htmlCode': '&#96;',
                    'name': '`',
                    'hex': '60'
                }, {
                    'oct': '141',
                    'symbol': 'a',
                    'dec': '97',
                    'bin': '01100001',
                    'htmlCode': '&#97;',
                    'name': 'a',
                    'hex': '61'
                }, {
                    'oct': '142',
                    'symbol': 'b',
                    'dec': '98',
                    'bin': '01100010',
                    'htmlCode': '&#98;',
                    'name': 'b',
                    'hex': '62'
                }, {
                    'oct': '143',
                    'symbol': 'c',
                    'dec': '99',
                    'bin': '01100011',
                    'htmlCode': '&#99;',
                    'name': 'c',
                    'hex': '63'
                }, {
                    'oct': '144',
                    'symbol': 'd',
                    'dec': '100',
                    'bin': '01100100',
                    'htmlCode': '&#100;',
                    'name': 'd',
                    'hex': '64'
                }, {
                    'oct': '145',
                    'symbol': 'e',
                    'dec': '101',
                    'bin': '01100101',
                    'htmlCode': '&#101;',
                    'name': 'e',
                    'hex': '65'
                }, {
                    'oct': '146',
                    'symbol': 'f',
                    'dec': '102',
                    'bin': '01100110',
                    'htmlCode': '&#102;',
                    'name': 'f',
                    'hex': '66'
                }, {
                    'oct': '147',
                    'symbol': 'g',
                    'dec': '103',
                    'bin': '01100111',
                    'htmlCode': '&#103;',
                    'name': 'g',
                    'hex': '67'
                }, {
                    'oct': '150',
                    'symbol': 'h',
                    'dec': '104',
                    'bin': '01101000',
                    'htmlCode': '&#104;',
                    'name': 'h',
                    'hex': '68'
                }, {
                    'oct': '151',
                    'symbol': 'i',
                    'dec': '105',
                    'bin': '01101001',
                    'htmlCode': '&#105;',
                    'name': 'i',
                    'hex': '69'
                }, {
                    'oct': '152',
                    'symbol': 'j',
                    'dec': '106',
                    'bin': '01101010',
                    'htmlCode': '&#106;',
                    'name': 'j',
                    'hex': '6A'
                }, {
                    'oct': '153',
                    'symbol': 'k',
                    'dec': '107',
                    'bin': '01101011',
                    'htmlCode': '&#107;',
                    'name': 'k',
                    'hex': '6B'
                }, {
                    'oct': '154',
                    'symbol': 'l',
                    'dec': '108',
                    'bin': '01101100',
                    'htmlCode': '&#108;',
                    'name': 'l',
                    'hex': '6C'
                }, {
                    'oct': '155',
                    'symbol': 'm',
                    'dec': '109',
                    'bin': '01101101',
                    'htmlCode': '&#109;',
                    'name': 'm',
                    'hex': '6D'
                }, {
                    'oct': '156',
                    'symbol': 'n',
                    'dec': '110',
                    'bin': '01101110',
                    'htmlCode': '&#110;',
                    'name': 'n',
                    'hex': '6E'
                }, {
                    'oct': '157',
                    'symbol': 'o',
                    'dec': '111',
                    'bin': '01101111',
                    'htmlCode': '&#111;',
                    'name': 'o',
                    'hex': '6F'
                }, {
                    'oct': '160',
                    'symbol': 'p',
                    'dec': '112',
                    'bin': '01110000',
                    'htmlCode': '&#112;',
                    'name': 'p',
                    'hex': '70'
                }, {
                    'oct': '161',
                    'symbol': 'q',
                    'dec': '113',
                    'bin': '01110001',
                    'htmlCode': '&#113;',
                    'name': 'q',
                    'hex': '71'
                }, {
                    'oct': '162',
                    'symbol': 'r',
                    'dec': '114',
                    'bin': '01110010',
                    'htmlCode': '&#114;',
                    'name': 'r',
                    'hex': '72'
                }, {
                    'oct': '163',
                    'symbol': 's',
                    'dec': '115',
                    'bin': '01110011',
                    'htmlCode': '&#115;',
                    'name': 's',
                    'hex': '73'
                }, {
                    'oct': '164',
                    'symbol': 't',
                    'dec': '116',
                    'bin': '01110100',
                    'htmlCode': '&#116;',
                    'name': 't',
                    'hex': '74'
                }, {
                    'oct': '165',
                    'symbol': 'u',
                    'dec': '117',
                    'bin': '01110101',
                    'htmlCode': '&#117;',
                    'name': 'u',
                    'hex': '75'
                }, {
                    'oct': '166',
                    'symbol': 'v',
                    'dec': '118',
                    'bin': '01110110',
                    'htmlCode': '&#118;',
                    'name': 'v',
                    'hex': '76'
                }, {
                    'oct': '167',
                    'symbol': 'w',
                    'dec': '119',
                    'bin': '01110111',
                    'htmlCode': '&#119;',
                    'name': 'w',
                    'hex': '77'
                }, {
                    'oct': '170',
                    'symbol': 'x',
                    'dec': '120',
                    'bin': '01111000',
                    'htmlCode': '&#120;',
                    'name': 'x',
                    'hex': '78'
                }, {
                    'oct': '171',
                    'symbol': 'y',
                    'dec': '121',
                    'bin': '01111001',
                    'htmlCode': '&#121;',
                    'name': 'y',
                    'hex': '79'
                }, {
                    'oct': '172',
                    'symbol': 'z',
                    'dec': '122',
                    'bin': '01111010',
                    'htmlCode': '&#122;',
                    'name': 'z',
                    'hex': '7A'
                }, {
                    'oct': '173',
                    'symbol': '{',
                    'dec': '123',
                    'bin': '01111011',
                    'htmlCode': '&#123;',
                    'name': '{',
                    'hex': '7B'
                }, {
                    'oct': '174',
                    'symbol': '|',
                    'dec': '124',
                    'bin': '01111100',
                    'htmlCode': '&#124;',
                    'name': '|',
                    'hex': '7C'
                }, {
                    'oct': '175',
                    'symbol': '}',
                    'dec': '125',
                    'bin': '01111101',
                    'htmlCode': '&#125;',
                    'name': '}',
                    'hex': '7D'
                }, {
                    'oct': '176',
                    'symbol': '~',
                    'dec': '126',
                    'bin': '01111110',
                    'htmlCode': '&#126;',
                    'name': '~',
                    'hex': '7E'
                }, {
                    'oct': '177',
                    'symbol': '',
                    'dec': '127',
                    'bin': '01111111',
                    'htmlCode': '&#127;',
                    'name': '删除',
                    'hex': '7F'
                }]
            }
        }
    }
</script>

<style scoped>

</style>
